provider_config:
  bms:
    ssh_user: "{{ USER }}"
    ssh_pwd:
    ssh_private_key: "{{ HOME }}/.ssh/id_rsa"
    domainsuffix: "{{ DOMAINSUFFIX }}"

instances:
  server1:
    ip: "{{ NODE_IP }}"
    provider: bms
    roles:
      analytics:
      analytics_snmp:
      analytics_alarm:
      analytics_database:
      config:
      config_database:
      control:
      webui:
      vrouter:
      openstack:
      openstack_compute:

global_configuration:
  CONTAINER_REGISTRY: "{{ CONTAINER_REGISTRY }}"
  REGISTRY_PRIVATE_INSECURE: True

contrail_configuration:
  CONTRAIL_CONTAINER_TAG: "{{ CONTRAIL_CONTAINER_TAG }}"
  CONFIG_DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "2"
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "2"
  JVM_EXTRA_OPTS: "-Xms1g -Xmx2g"
  VROUTER_ENCRYPTION: FALSE
  LOG_LEVEL: SYS_DEBUG
  CLOUD_ORCHESTRATOR: openstack
  OPENSTACK_VERSION: "{{ OPENSTACK_VERSION }}"
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3
  SSL_ENABLE: "{{ SSL_ENABLE }}"
  RABBITMQ_USE_SSL: "{{ SSL_ENABLE }}"
  CASSANDRA_SSL_ENABLE: "{{ SSL_ENABLE }}"
# Default counfiguration params in the section below will be set as ENV variables for all proviosioner containers
default_configuration:
#  VXLAN_VN_ID_MODE: automatic
kolla_config:
  kolla_globals:
    enable_haproxy: no
    enable_ironic: no
    enable_swift: no
    enable_barbican: no
    nova_compute_virt_type: qemu
  kolla_passwords:
    keystone_admin_password: contrail123
