provider_config:
  bms:
    ssh_user: "{{ USER }}"
    ssh_pwd:
    ssh_private_key: "{{ HOME }}/.ssh/id_rsa"
    domainsuffix: "{{ DOMAINSUFFIX }}"

instances:
  server1:
    ip: "{{ NODE_IP }}"
    provider: bms
    roles:
      analytics:
      analytics_snmp:
      analytics_alarm:
      analytics_database:
      config:
      config_database:
      control:
      webui:
      vrouter:
      k8s_master:
      k8s_node:
      kubemanager:
global_configuration:
  CONTAINER_REGISTRY: "{{ CONTAINER_REGISTRY }}"
  REGISTRY_PRIVATE_INSECURE: True
default_configuration:
  VXLAN_VN_ID_MODE: automatic
contrail_configuration:
  CONTRAIL_CONTAINER_TAG: "{{ CONTRAIL_CONTAINER_TAG }}"
  CONFIG_DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "2"
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "2"
  JVM_EXTRA_OPTS: "-Xms1g -Xmx2g"
  VROUTER_ENCRYPTION: FALSE
  LOG_LEVEL: SYS_DEBUG
  CLOUD_ORCHESTRATOR: kubernetes
  KUBERNETES_PUBLIC_FIP_POOL:
    domain: default-domain
    name: __fip_pool_public__
    network: __public__
    project: k8s-default
  SSL_ENABLE: "{{ SSL_ENABLE }}"
  RABBITMQ_USE_SSL: "{{ SSL_ENABLE }}"
  CASSANDRA_SSL_ENABLE: "{{ SSL_ENABLE }}"
